### ISSUE TITLE
Server inaccessible

### ISSUE THREAD

**Issue by NickHam13** [regimensocial/Citrahold-3DS#1]
Been consistently getting this error while trying to set up the app on my 3DS. It works fine on my PC, though.

**Comment by Quackad** [comment]
Yeah, I've been having the same issue unfortunately

**Comment by Shiggs921** [comment]
Having the same issue too, seem odd since it works from the PC side.

**Comment by regimensocial** [comment]
So sorry for taking such a long time to notice this.

This is now fixed in the latest 3DS build, [v1.1.1](https://github.com/regimensocial/Citrahold-3DS/releases/tag/v1.1.1).
