### ISSUE TITLE
Can't see text on long list

### ISSUE THREAD

**Issue by purekimwater** [regimensocial/Citrahold-3DS#5]
Hi, love the service.

I have a long list of games, but the text on the top screen can only zoom/zoom out.
Which is not very useful when I want a game that's way on the bottom,
I have to zoom out so much, and by then the text is so small that I can't read them.

Can't the top screen just scroll
instead of zoom and zoom out?

Thanks.

**Comment by regimensocial** [comment]
Hi there, I am aware of this issue and planning to look into it soon when I get some free time.

Sorry about this oversight but it should be fixed in a few weeks I hope

**Comment by regimensocial** [comment]
Hi. 

I've redesigned the directory menu in the latest version so that this should be "fixed".

Sorry for the delay!
